name: Build .NET DLL

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore ./Assembly-CSharp.csproj

    - name: Build project
      run: dotnet build ./Assembly-CSharp.csproj --configuration Release --no-restore

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Assembly-CSharp-DLL
        path: |
          **/bin/Release/**/*.dll
          **/bin/Release/**/*.pdb
        retention-days: 30

    - name: Display build output
      run: |
        echo "Build completed successfully!"
        find . -path "*/bin/Release/*.dll" -exec ls -la {} \;
